spring.application.name=clinicaocupacional
jwt.secret=clinicaOcupacionalSecretKey2026BackendSeguro
jwt.expiration=86400000
spring.datasource.url=jdbc:mysql://localhost:3306/bd_clinica
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
# Logs detallados para debug
logging.level.org.springframework.security=DEBUG
logging.level.clinica.com.example=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Suprimir warning de Thymeleaf
spring.thymeleaf.check-template-location=false

# Suprimir warning de open-in-view
spring.jpa.open-in-view=false

# Ver SQL generado
spring.jpa.show-sql=true

# Ver error real en login
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
